from pathlib import Path

DATASET_ROOT = Path("/home/pc-04/Research/_datasets")

DATASET_LOCATION = "YJP-Lvl04"
DATASET_TYPE = "SonyA7Mk4"
DATASET_DATE = "250828"
DATASET_NO = "00"

if DATASET_TYPE == "SonyA7Mk4":
    DATA_COMPLETENESS = "Full"
    DATA_RESOLUTION = "Quarter"
    DATA_VARIANT = f"{DATA_COMPLETENESS}Set_{DATA_RESOLUTION}Res"
elif DATASET_TYPE == "MatterportPro3":
    DATA_COMPLETENESS = "Full"
    DATA_RESOLUTION = "Full"
    DATA_VARIANT = f"{DATA_COMPLETENESS}Set_{DATA_RESOLUTION}Res"
elif DATASET_TYPE == "Insta360X4":
    EVERY_SECONDS: int = 3
    CAMERA: str = "front" 
    DATA_VARIANT: Path = f"every_{EVERY_SECONDS}" / CAMERA

DATASET_NAME = f"{DATASET_LOCATION}_{DATASET_TYPE}_{DATASET_DATE}-{DATASET_NO}"
DATASET_PATH = Path(DATASET_ROOT) / DATASET_NAME