from pathlib import Path

DATASET_ROOT = Path("/home/pc-04/Research/_datasets")

DATASET_LOCATION = "YJP-Lvl04"
DATASET_TYPE = "Insta360X4"
DATASET_DATE = "250828"
DATASET_NO = "00"

DATASET_NAME = f"{DATASET_LOCATION}_{DATASET_TYPE}_{DATASET_DATE}-{DATASET_NO}"

DATASET_PATH = Path(DATASET_ROOT) / DATASET_NAME