from pathlib import Path

DATASET_ROOT = Path("/home/pc-04/Research/_datasets")

DATASET_LOCATION = "IMU-Testing"
DATASET_TYPE = "InstaX4"
DATASET_DATE = "250903"
DATASET_NO = "00"

DATASET_NAME = f"{DATASET_LOCATION}_{DATASET_TYPE}_{DATASET_DATE}-{DATASET_NO}"

DATASET_PATH = Path(DATASET_ROOT) / DATASET_NAME